[package]
edition = "2021"
name = "dagskra-lib"
version = "0.2.0"

[dependencies]
chrono = "0.4"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
tracing = "0.1"
