[package]
description = "Library support for dagskra-web"
edition = "2021"
name = "dagskra-lib"
version = "0.1.2"

[dependencies]
chrono = "0.4"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_with = "2"
